SELECT * FROM DM_MEDICAID.CLAIM_ENCOUNTER_OTHER;

SELECT * FROM DM_MEDICAID.REF_RECORD_CODE_H002;

SELECT * FROM DM_MEDICAID.dim_mcaid_recip_current;



SELECT COUNT(DISTINCT claim_trans_id_w004) FROM DM_MEDICAID.CLAIM_ENCOUNTER_OTHER
where date_of_service_3013>DATE'30-NOV-21';--14036

CREATE TABLE KYOU.FIRSTTRY AS
SELECT MAX (claim_trans_id_w004) AS MAX_CLAIM_DATE FROM DM_MEDICAID.CLAIM_ENCOUNTER_OTHER;

SELECT * FROM SHARED_TABLES.CNF_DIM_DIAGNOSIS;


SELECT owner, table_name FROM all_tables
WHERE  OWNER IN ('KYOU');

SELECT DISTINCT Record_Code_H002 AS CODE, COUNT(RECORD_CODE_H002 = CODE) AS COUNT_   FROM DM_MEDICAID_NET.NET_SERVICE_PHARMACY
where date_of_service_3013>DATE'30-NOV-21';

SELECT COUNT (ALL RECORD_CODE_H002)  FROM DM_MEDICAID.REF_Record_Code_H002
WHERE RECORD_CODE_H002 IN ('4');


SELECT COUNT (ALL RECORD_CODE_H002)  FROM DM_MEDICAID_NET.NET_SERVICE_PHARMACY
WHERE RECORD_CODE_H002 IN ('4') and  date_of_service_3013>DATE'2020-12-31';--184960368

SELECT record_code_h002, primary_diag_code_3006, sec_diag_code_3007, diagnosis_concat FROM DM_MEDICAID_NET.NET_SERVICE_PHARMACY;

DESCRIBE DM_MEDICAID_NET.NET_SERVICE_PHARMACY;
SELECT  * FROM DM_MEDICAID_NET.NET_SERVICE_PHARMACY;
SELECT  * FROM DM_MEDICAID_NET.NET_DIAGNOSIS_CHILD;
SELECT  * FROM MEDICAID.Ref_claim_type_e0141;
SELECT  * FROM DM_MEDICAID.REF_EMEDNY_COMBINED_CODE;
SELECT  * FROM DM_MEDICAID.OMH_Rate_Code_Serv_Group;
SELECT  * FROM DM_MEDICAID.CLAIM_PROCEDURE;


--PAGE 34 PPT 2
--Sample SQL- identifying after-hour clinic FFS by procedure code
select a.PROVIDER_ENTITY_ID_E2135, a.PROVIDER_ID_2001, a.PROVIDER_ENTITY_NAME_E2136, 
    c.COUNTY_LABEL, count(distinct ORIGINAL_CLAIM_NUMBER_W026 ) as n_ocrn, 
    sum(AMT_PAID_CLAIM_WITHOUT_PGP) as amt_paid,  
    count(distinct case when (INSTR(PROC_CONCAT, '99050', 1, 1) >0 or INSTR(PROC_CONCAT, '99051', 1, 1) >0) then ORIGINAL_CLAIM_NUMBER_W026 end) as n_claims_proc
from 
    (
    select  PC.PROVIDER_ENTITY_ID_E2135, PC.PROVIDER_ENTITY_NAME_E2136, SERV.PROVIDER_ID_2001, SERV.CATGY_OF_SERV_2019, 
        SERV.PROC_CONCAT, SERV.recipient_id_1010, SERV.date_of_service_3013, SERV.recipient_age_at_dos, SERV.original_claim_number_w026, 
        SERV.AMT_PAID_CLAIM_WITHOUT_PGP, SERV.invoice_type_3301,SERV.RECORD_CODE_H002, SERV.PROVIDER_COUNTY_ADDR_2017  
    from DM_MEDICAID_NET.NET_SERVICE_PHARMACY SERV, DM_MEDICAID.PROVIDER_CURRENT PC, MEDICAID.OMH_RATE_CODE_GROUP RG 
    where  
        SERV.RECORD_CODE_H002=3 and 
        SERV.RATE_CODE_2078=RG.RATE_CODE  and  
        RG.RATE_CODE_GROUP='CLINIC' and 
        SERV.invoice_type_3301 in ('01','05') and 
        SERV.PROVIDER_ID_2001=PC.PROVIDER_ID_2001 and 
        SERV.DATE_OF_SERVICE_3013 between to_date('01-JAN-2013') and to_date('31-DEC-2013') 
    ) a, 
    medicaid.PROVIDER_LOCATION_ADDRESS b, 
    shared_tables.CNF_DIM_COUNTY c
where a.provider_id_2001=b.provider_id_2001 and B.PROVIDER_LOCATOR_CODE_2034='001' and b.PROVIDER_COUNTY_ADDR_2017=c.MMIS_COUNTY_CODE 
group by a.PROVIDER_ENTITY_ID_E2135, a.PROVIDER_ID_2001, a.PROVIDER_ENTITY_NAME_E2136,c.COUNTY_LABEL;


--Sample SQL- identifying MH inpatient services with a SUD Dx code on any diagnosis field 
SELECT count(distinct recipient_id_1010) cnt_recip, 
       count(distinct ORIGINAL_CLAIM_NUMBER_W026) as cnt 
    from  DM_MEDICAID_NET.NET_SERVICE_PHARMACY
    where DATE_DISCHARGE_3108  between '01-JAN-2013' AND '31-DEC-2013'
        AND RATE_CODE_2078 in ('2852', '2858', '4001', '4002')   
        and  ( DIAGNOSIS_CONCAT like '%|291%'
            or DIAGNOSIS_CONCAT like '%|292%'
            or DIAGNOSIS_CONCAT like '%|303%'
            or DIAGNOSIS_CONCAT like '%|304%'
            or DIAGNOSIS_CONCAT like '%|305%'
            or DIAGNOSIS_CONCAT like '%|V791%');



SELECT  * FROM SHARED_TABLES.ALLMEDSWITHNDC;


--PPT 4 PROVDER

SELECT  * FROM DM_MEDICAID.Fact_Claim_Encounter;


--PPT 5 RECIPIENTS
SELECT * FROM DM_MEDICAID.DIM_MEDICAID_RECIPIENT;
SELECT * FROM DM_MEDICAID.OMH_RECIPIENT_BASE;

SELECT * FROM DM_MEDICAID.fact_claim_encounter;
SELECT * FROM DM_MEDICAID.CLAIM_PROCEDURE;

SELECT count(claim_trans_id_w004) FROM DM_MEDICAID.CLAIM_PROCEDURE
where date_procedure_3092 > TO_DATE('30-NOV-2021'); --
SELECT count(distinct claim_trans_id_w004) FROM DM_MEDICAID.CLAIM_PROCEDURE;


SELECT * FROM DM_MEDICAID.DIM_MCAID_RECIP_CURRENT;
SELECT * FROM DM_MEDICAID.DIM_MEDICAID_RECIPIENT;
SELECT * FROM DM_MEDICAID.Ref_Claim_Status_Type_C188;




SELECT * FROM DM_MEDICAID.REF_EMEDNY_COMBINED_CODE
where table_name = 'Ref_Recipient_County_1220'  ;


SELECT * FROM Shared_tables.CNF_DIM_DIAGNOSIS   ;
SELECT * FROM DM_MEDICAID_NET.NET_DIAGNOSIS_CHILD ;





